




2025-08-15 09:12:51.533235+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:12:52.389636+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:12:52.905717+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:12:53.451928+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:12:53.986261+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:12:54.663113+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:12:54.991808+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:12:55.331554+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:12:55.681408+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:12:55.681430+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:17:12.502695+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:17:13.254304+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:17:13.699712+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:17:14.482207+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:17:15.084681+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:17:15.567293+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:17:16.006094+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:17:16.645152+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:17:17.221937+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:17:17.221974+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:25:02.079041+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:25:04.120471+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:25:05.307353+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:25:05.981966+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:25:06.677553+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:25:07.010975+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:25:07.362071+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:25:07.703673+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:25:08.058273+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:25:08.058295+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:33:33.456472+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:33:34.812876+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:33:35.383326+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:33:35.924319+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:33:36.469251+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:33:36.922463+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:33:37.286282+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:33:37.642689+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:33:38.095981+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:33:38.096002+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:35:14.394320+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:35:15.010609+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:35:15.456910+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:35:15.928663+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:35:16.405715+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:35:16.788405+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:35:17.171893+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:35:17.533044+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:35:17.894225+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:35:17.894247+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:41:34.377647+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:41:35.058012+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:41:35.539035+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:41:36.095498+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:41:36.631161+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:41:37.047185+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:41:37.388151+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:41:37.775195+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:41:38.136131+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:41:38.136154+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:42:42.696835+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:42:43.379880+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:42:43.839304+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:42:44.478740+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:42:44.977704+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:42:45.376733+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:42:45.721957+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:42:46.108279+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:42:46.477882+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:42:46.477903+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 09:50:38.260710+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 09:50:38.945746+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 09:50:39.947384+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 09:50:40.414588+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 09:50:40.905110+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 09:50:41.263512+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 09:50:41.622204+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 09:50:42.001786+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 09:50:42.371697+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 09:50:42.371720+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 10:14:12.517107+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 10:14:15.536031+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 10:14:16.558659+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 10:14:17.219601+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 10:14:17.951460+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 10:14:18.442336+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 10:14:18.821579+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 10:14:19.189750+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 10:14:19.574724+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 10:14:19.574747+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 10:22:48.752505+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 10:22:50.027458+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 10:22:50.577613+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 10:22:51.136640+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 10:22:51.742931+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 10:22:52.281639+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 10:22:52.658521+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 10:22:53.013694+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 10:22:53.431532+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 10:22:53.431555+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 10:57:35.541924+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 10:57:37.438584+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 10:57:38.086235+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 10:57:38.792187+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 10:57:39.602673+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 10:57:40.049892+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 10:57:41.796202+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 10:57:42.305558+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 10:57:43.103404+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 10:57:43.103426+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 11:03:12.523632+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 11:03:13.224981+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 11:03:13.684087+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 11:03:14.147961+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 11:03:14.622333+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 11:03:14.957801+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 11:03:15.610835+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 11:03:16.441803+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 11:03:17.045704+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 11:03:17.045726+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 11:14:53.945631+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 11:14:56.626108+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 11:14:57.422689+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 11:14:58.537656+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 11:14:59.661295+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 11:15:00.774324+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 11:15:01.987196+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 11:15:02.492238+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 11:15:03.487480+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 11:15:03.487504+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 11:20:11.675147+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 11:20:12.970717+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 11:20:13.640521+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 11:20:14.224276+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 11:20:14.711684+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 11:20:15.231756+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 11:20:15.625239+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 11:20:15.982679+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 11:20:16.486054+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 11:20:16.486077+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 11:45:12.121169+00:00 : upload_to_database_historical.py has been initiated.

Traceback (most recent call last):
  File "/home/ec2-user/vivacity/upload_to_database_historical.py", line 95, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ec2-user/vivacity/upload_to_database_historical.py", line 33, in main
    response = await response_handler(url, headers, params)
  File "/home/ec2-user/vivacity/imports/upload_to_database_historical_helper.py", line 80, in response_handler
    response = requests.get(url, headers=headers, params=params)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 494, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt





2025-08-15 11:45:23.012984+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 11:45:23.743962+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 11:45:24.681561+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 11:45:25.693151+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 11:45:26.512653+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 11:45:26.962488+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 11:45:27.502023+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 11:45:27.904746+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 11:45:28.860322+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 11:45:28.860343+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 12:54:56.908305+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 12:54:59.143445+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 12:54:59.854875+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 12:55:00.530152+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 12:55:01.214011+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 12:55:01.605760+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 12:55:05.519174+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 12:55:05.909023+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 12:55:06.324930+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 12:55:06.324956+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:07:43.941063+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:07:46.441428+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:07:47.418441+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:07:48.465668+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:07:49.396515+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:07:50.008269+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:07:50.774399+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:07:51.507676+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:07:52.167938+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:07:52.167961+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:12:02.276596+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:12:03.027950+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:12:03.695643+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:12:04.330059+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:12:04.969150+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:12:05.456249+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:12:05.936231+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:12:06.427731+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:12:06.800099+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:12:06.800123+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:13:08.129889+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:13:08.829708+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:13:09.418920+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:13:09.927763+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:13:10.730808+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:13:11.246876+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:13:11.628739+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:13:12.055223+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:13:12.436682+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:13:12.436712+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:13:46.874904+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:13:47.556112+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:13:48.109457+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:13:48.556356+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:13:49.103207+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:13:49.452693+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:13:50.039979+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:13:50.406891+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:13:50.801416+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:13:50.801442+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:16:14.649182+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:16:15.269264+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:16:15.828134+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:16:16.806843+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:16:17.322755+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:16:17.682128+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:16:18.052797+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:16:18.409609+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:16:19.327611+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:16:19.327632+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:21:15.771127+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:21:18.174444+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:21:18.712080+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:21:19.188905+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:21:19.634081+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:21:20.009863+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:21:20.698058+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:21:21.069732+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:21:21.456193+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:21:21.456216+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 13:30:08.255070+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 13:30:11.121640+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 13:30:11.989429+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 13:30:12.713327+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 13:30:13.350848+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 13:30:13.753931+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 13:30:14.143675+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 13:30:14.758383+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 13:30:15.301295+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 13:30:15.301316+00:00 : Exiting upload_to_database_historical.py...










2025-08-15 14:00:02.112269+00:00 : upload_to_database_historical.py has been initiated.

2025-08-15 14:00:05.339100+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-15 14:00:06.058955+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-15 14:00:06.947903+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-15 14:00:07.572657+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-15 14:00:07.942869+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-15 14:00:08.316042+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-15 14:00:08.688979+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-15 14:00:09.066531+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-15 14:00:09.066553+00:00 : Exiting upload_to_database_historical.py...










2025-08-18 15:28:48.683085+00:00 : upload_to_database_historical.py has been initiated.

2025-08-18 15:28:50.769257+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-18 15:28:52.153543+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-18 15:28:53.466530+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-18 15:28:54.942552+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-18 15:28:55.342275+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-18 15:28:55.752579+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-18 15:28:56.365111+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-18 15:28:57.014862+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-18 15:28:57.014884+00:00 : Exiting upload_to_database_historical.py...










2025-08-18 17:17:24.815575+00:00 : upload_to_database_historical.py has been initiated.

2025-08-18 17:17:24.864232+00:00 : (Connection) Error : An Error has occurred while connecting to the database

2025-08-18 17:17:25.865468+00:00 : (Connection) Attempt no.1 failed, retrying if possible...

2025-08-18 17:17:25.911124+00:00 : (Connection) Error : An Error has occurred while connecting to the database

2025-08-18 17:17:26.912478+00:00 : (Connection) Attempt no.2 failed, retrying if possible...

2025-08-18 17:17:26.961452+00:00 : (Connection) Error : An Error has occurred while connecting to the database

2025-08-18 17:17:27.962723+00:00 : (Connection) Attempt no.3 failed, retrying if possible...

2025-08-18 17:17:31.015122+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-18 17:17:32.579682+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-18 17:17:34.858518+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-18 17:17:36.382545+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-18 17:17:37.738692+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-18 17:17:39.327890+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-18 17:17:40.770117+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-18 17:17:41.526634+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-18 17:17:41.526657+00:00 : Exiting upload_to_database_historical.py...










2025-08-18 17:35:21.120699+00:00 : upload_to_database_historical.py has been initiated.

2025-08-18 17:35:23.455751+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-18 17:35:24.250987+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-18 17:35:25.616562+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-18 17:35:27.085374+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-18 17:35:28.500682+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-18 17:35:28.903668+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-18 17:35:29.954707+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-18 17:35:30.477904+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-18 17:35:30.477943+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 10:54:08.812239+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 10:54:10.634437+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 10:54:11.587827+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 10:54:13.043103+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 10:54:13.786972+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 10:54:14.177743+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 10:54:14.628329+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 10:54:15.087704+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 10:54:15.947453+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 10:54:15.947476+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 10:58:46.381056+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 10:58:47.222601+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 10:58:47.932962+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 10:58:48.405215+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 10:58:48.988971+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 10:58:49.399243+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 10:58:49.739770+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 10:58:50.149136+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 10:58:50.575998+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 10:58:50.576019+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 11:04:04.755336+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 11:04:05.314455+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 11:04:05.778224+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 11:04:06.249814+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 11:04:06.748602+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 11:04:07.141879+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 11:04:07.505515+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 11:04:07.905641+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 11:04:08.299527+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 11:04:08.299547+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 11:45:06.449479+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 11:45:08.669637+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 11:45:09.798390+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 11:45:11.012105+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 11:45:12.506510+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 11:45:12.942137+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 11:45:13.532132+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 11:45:13.996534+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 11:45:14.626401+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 11:45:14.626435+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 11:56:36.980270+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 11:56:39.270863+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 11:56:39.903111+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 11:56:40.543575+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 11:56:41.853459+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 11:56:42.232785+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 11:56:43.333730+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 11:56:44.424644+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 11:56:45.007828+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 11:56:45.007862+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 12:00:07.246565+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 12:00:09.463654+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 12:00:10.265777+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 12:00:11.419811+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 12:00:12.701754+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 12:00:13.208474+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 12:00:15.564183+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 12:00:16.048328+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 12:00:17.110160+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 12:00:17.110183+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 12:03:29.407746+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 12:03:29.986252+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 12:03:30.536306+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 12:03:31.093332+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 12:03:31.702972+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 12:03:32.057500+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 12:03:32.479984+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 12:03:32.836980+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 12:03:33.273260+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 12:03:33.273282+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 12:04:02.506039+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 12:04:03.043470+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 12:04:03.590415+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 12:04:04.191903+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 12:04:04.690096+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 12:04:05.205326+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 12:04:05.583315+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 12:04:06.007363+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 12:04:06.518034+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 12:04:06.518055+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 12:05:44.837802+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 12:05:46.029538+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 12:05:46.615079+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 12:05:47.176277+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 12:05:48.268749+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 12:05:48.612368+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 12:05:49.238220+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 12:05:49.592007+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 12:05:49.962088+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 12:05:49.962108+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 12:06:31.525531+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 12:06:32.337454+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 12:06:32.904565+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 12:06:33.672759+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 12:06:34.226106+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 12:06:34.667369+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 12:06:35.039512+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 12:06:36.861391+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 12:06:37.292214+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 12:06:37.292235+00:00 : Exiting upload_to_database_historical.py...










2025-08-19 14:00:01.067413+00:00 : upload_to_database_historical.py has been initiated.

2025-08-19 14:00:07.147923+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-19 14:00:08.433591+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-19 14:00:09.145617+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-19 14:00:10.536993+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-19 14:00:10.953293+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-19 14:00:11.514535+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-19 14:00:12.077550+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-19 14:00:12.747659+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-19 14:00:12.747682+00:00 : Exiting upload_to_database_historical.py...





/usr/bin/python3: can't find '__main__' module in '/home/ec2-user/vivacity/'
/usr/bin/python3: can't find '__main__' module in '/home/ec2-user/vivacity/'





2025-08-20 10:26:40.853634+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:26:42.920222+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:26:44.214676+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:26:45.508160+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:26:48.087166+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:26:48.513482+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:26:49.380816+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:26:50.234242+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:26:50.733077+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:26:50.733099+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:31:18.354271+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:31:19.030676+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:31:19.723144+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:31:20.368988+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:31:20.929711+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:31:21.308634+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:31:21.760768+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:31:22.240090+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:31:22.678483+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:31:22.678505+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:33:47.557666+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:33:48.091088+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:33:48.582098+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:33:49.101238+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:33:49.603637+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:33:49.970374+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:33:50.417271+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:33:50.876299+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:33:51.281190+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:33:51.281227+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:35:12.762757+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:35:15.130948+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:35:15.719101+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:35:16.280761+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:35:16.814774+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:35:17.214403+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:35:17.687441+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:35:18.194111+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:35:18.933136+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:35:18.933165+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:36:30.390995+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:36:30.883154+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:36:31.360843+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:36:31.825933+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:36:32.290301+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:36:32.644811+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:36:33.234877+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:36:33.589716+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:36:33.977588+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:36:33.977610+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:37:03.574702+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:37:04.069125+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:37:04.572321+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:37:05.084291+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:37:05.586971+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:37:05.933560+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:37:06.272754+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:37:06.668233+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:37:07.219409+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:37:07.219430+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:37:52.590664+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:37:53.113855+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:37:53.567056+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:37:54.048510+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:37:54.559860+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:37:54.912202+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:37:55.922046+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:37:56.305945+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:37:56.914418+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:37:56.914439+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:38:11.869018+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:38:12.501581+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:38:13.007354+00:00 : Successful insertion of bucket size = 60m at cycle = 2

Traceback (most recent call last):
  File "/home/ec2-user/vivacity/upload_to_database_historical.py", line 95, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ec2-user/vivacity/upload_to_database_historical.py", line 33, in main
    response = await response_handler(url, headers, params)
  File "/home/ec2-user/vivacity/imports/upload_to_database_historical_helper.py", line 79, in response_handler
    response = requests.get(url, headers=headers, params=params)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 494, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.9/socket.py", line 716, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt





2025-08-20 10:44:26.140703+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:44:27.152371+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:44:27.678409+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:44:28.208287+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:44:28.811093+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:44:29.178400+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:44:29.636303+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:44:30.235267+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:44:30.736539+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:44:30.736575+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:45:13.793106+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:45:14.349559+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 10:45:16.741751+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 10:45:17.792974+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 10:45:18.609317+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 10:45:18.975174+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 10:45:19.826949+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 10:45:20.286215+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 10:45:20.757583+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 10:45:20.757605+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 10:54:42.643587+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 10:54:43.932581+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:44.933858+00:00 : (Insertion) Attempt no.1 failed, retrying if possible...

2025-08-20 10:54:44.933894+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:45.934600+00:00 : (Insertion) Attempt no.2 failed, retrying if possible...

2025-08-20 10:54:45.934650+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:46.935773+00:00 : (Insertion) Attempt no.3 failed, retrying if possible...

2025-08-20 10:54:46.935808+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:47.937028+00:00 : (Insertion) Attempt no.4 failed, retrying if possible...

2025-08-20 10:54:47.937065+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:48.938279+00:00 : (Insertion) Attempt no.5 failed, retrying if possible...

2025-08-20 10:54:48.938329+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:49.939630+00:00 : (Insertion) Attempt no.6 failed, retrying if possible...

2025-08-20 10:54:49.939667+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:50.940926+00:00 : (Insertion) Attempt no.7 failed, retrying if possible...

2025-08-20 10:54:50.940963+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:51.941292+00:00 : (Insertion) Attempt no.8 failed, retrying if possible...

2025-08-20 10:54:51.941330+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:52.942539+00:00 : (Insertion) Attempt no.9 failed, retrying if possible...

2025-08-20 10:54:52.942577+00:00 : (Insertion) Error : ERROR HAS OCCURRED IN INSERTION

2025-08-20 10:54:53.943844+00:00 : (Insertion) Error unresolved - exiting program










2025-08-20 11:12:10.809830+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:12:12.928998+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:12:13.734872+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:12:14.552366+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:12:15.739145+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:12:18.020570+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:12:18.467262+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:12:19.345511+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:12:19.823093+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:12:19.823114+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 11:13:40.361529+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:13:41.131752+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:13:41.707205+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:13:42.518810+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:13:43.054171+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:13:43.693254+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:13:44.329298+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:13:44.736997+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:13:45.308094+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:13:45.308118+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 11:21:20.534706+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:21:22.587205+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:21:24.220696+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:21:25.048483+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:21:25.889446+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:21:26.231925+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:21:26.612236+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:21:27.931127+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:21:28.402306+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:21:28.402328+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 11:22:52.903224+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:22:53.508393+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:22:54.270248+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:22:56.265917+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:22:57.113486+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:22:57.481177+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:22:57.876401+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:22:58.254361+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:22:58.633660+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:22:58.633681+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 11:31:26.040308+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:31:37.680644+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:31:38.440670+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:31:39.201420+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:31:39.934899+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:31:40.351015+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:31:40.704043+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:31:41.736785+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:31:42.305794+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:31:42.305816+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 11:32:43.296768+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 11:32:43.799192+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 11:32:44.307964+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 11:32:45.428740+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 11:32:46.103569+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 11:32:46.914354+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 11:32:47.287318+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 11:32:47.814745+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 11:32:48.324509+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 11:32:48.324535+00:00 : Exiting upload_to_database_historical.py...










2025-08-20 14:00:01.064690+00:00 : upload_to_database_historical.py has been initiated.

2025-08-20 14:00:03.365339+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-20 14:00:04.582959+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-20 14:00:05.451093+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-20 14:00:06.324882+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-20 14:00:09.102282+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-20 14:00:09.614445+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-20 14:00:10.667365+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-20 14:00:11.180206+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-20 14:00:11.180229+00:00 : Exiting upload_to_database_historical.py...










2025-08-21 08:22:01.032716+00:00 : upload_to_database_historical.py has been initiated.

2025-08-21 08:22:03.265857+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-21 08:22:04.361428+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-21 08:22:05.408040+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-21 08:22:08.471537+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-21 08:22:09.101902+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-21 08:22:09.602417+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-21 08:22:10.128047+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-21 08:22:10.763431+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-21 08:22:10.763453+00:00 : Exiting upload_to_database_historical.py...





Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'





2025-08-21 14:11:37.342349+00:00 : upload_to_database_historical.py has been initiated.

2025-08-21 14:11:40.384738+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:41.403603+00:00 : (Insertion) Attempt no.1 failed, retrying if possible...

2025-08-21 14:11:41.404578+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:42.409323+00:00 : (Insertion) Attempt no.2 failed, retrying if possible...

2025-08-21 14:11:42.410356+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:43.412589+00:00 : (Insertion) Attempt no.3 failed, retrying if possible...

2025-08-21 14:11:43.413848+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:44.433788+00:00 : (Insertion) Attempt no.4 failed, retrying if possible...

2025-08-21 14:11:44.435049+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:45.453735+00:00 : (Insertion) Attempt no.5 failed, retrying if possible...

2025-08-21 14:11:45.454901+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:46.471157+00:00 : (Insertion) Attempt no.6 failed, retrying if possible...

2025-08-21 14:11:46.472776+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:47.478958+00:00 : (Insertion) Attempt no.7 failed, retrying if possible...

2025-08-21 14:11:47.480116+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:48.489494+00:00 : (Insertion) Attempt no.8 failed, retrying if possible...

2025-08-21 14:11:48.491101+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:49.492328+00:00 : (Insertion) Attempt no.9 failed, retrying if possible...

2025-08-21 14:11:49.493493+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-21 14:11:48.282068+00:00 : (Insertion) Error unresolved - exiting program





Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 77
    except
          ^
SyntaxError: expected ':'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 77
    except
          ^
SyntaxError: expected ':'





2025-08-22 06:19:26.570392+00:00 : upload_to_database_historical.py has been initiated.

2025-08-22 06:19:26.574812+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:27.575307+00:00 : (Connection) Attempt no.1 failed, retrying if possible...

2025-08-22 06:19:27.578375+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:28.598509+00:00 : (Connection) Attempt no.2 failed, retrying if possible...

2025-08-22 06:19:28.601231+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:29.635706+00:00 : (Connection) Attempt no.3 failed, retrying if possible...

2025-08-22 06:19:29.638821+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:30.640221+00:00 : (Connection) Attempt no.4 failed, retrying if possible...

2025-08-22 06:19:30.643248+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:31.644731+00:00 : (Connection) Attempt no.5 failed, retrying if possible...

2025-08-22 06:19:31.647947+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:32.649366+00:00 : (Connection) Attempt no.6 failed, retrying if possible...

2025-08-22 06:19:32.652101+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:33.653544+00:00 : (Connection) Attempt no.7 failed, retrying if possible...

2025-08-22 06:19:33.657326+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:34.658792+00:00 : (Connection) Attempt no.8 failed, retrying if possible...

2025-08-22 06:19:34.661415+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:35.662971+00:00 : (Connection) Attempt no.9 failed, retrying if possible...

2025-08-22 06:19:35.665484+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 06:19:36.680801+00:00 : (Connection) Error unresolved - exiting program










2025-08-22 08:06:16.726247+00:00 : upload_to_database_historical.py has been initiated.

2025-08-22 08:06:16.730111+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:17.730468+00:00 : (Connection) Attempt no.1 failed, retrying if possible...

2025-08-22 08:06:17.731819+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:18.733000+00:00 : (Connection) Attempt no.2 failed, retrying if possible...

2025-08-22 08:06:18.734040+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:19.737891+00:00 : (Connection) Attempt no.3 failed, retrying if possible...

2025-08-22 08:06:19.739152+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:20.740256+00:00 : (Connection) Attempt no.4 failed, retrying if possible...

2025-08-22 08:06:20.741345+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:21.741557+00:00 : (Connection) Attempt no.5 failed, retrying if possible...

2025-08-22 08:06:21.742696+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:22.742920+00:00 : (Connection) Attempt no.6 failed, retrying if possible...

2025-08-22 08:06:22.744082+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:23.744356+00:00 : (Connection) Attempt no.7 failed, retrying if possible...

2025-08-22 08:06:23.746899+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:24.747544+00:00 : (Connection) Attempt no.8 failed, retrying if possible...

2025-08-22 08:06:24.748641+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:25.749236+00:00 : (Connection) Attempt no.9 failed, retrying if possible...

2025-08-22 08:06:25.750254+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:06:26.751441+00:00 : (Connection) Error unresolved - exiting program










2025-08-22 08:12:37.626659+00:00 : upload_to_database_historical.py has been initiated.

2025-08-22 08:12:37.629968+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:38.632667+00:00 : (Connection) Attempt no.1 failed, retrying if possible...

2025-08-22 08:12:38.633871+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:39.636515+00:00 : (Connection) Attempt no.2 failed, retrying if possible...

2025-08-22 08:12:39.638574+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:40.641272+00:00 : (Connection) Attempt no.3 failed, retrying if possible...

2025-08-22 08:12:40.643026+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:41.645388+00:00 : (Connection) Attempt no.4 failed, retrying if possible...

2025-08-22 08:12:41.646938+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:42.649252+00:00 : (Connection) Attempt no.5 failed, retrying if possible...

2025-08-22 08:12:42.650760+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:43.653042+00:00 : (Connection) Attempt no.6 failed, retrying if possible...

2025-08-22 08:12:43.654105+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:44.655268+00:00 : (Connection) Attempt no.7 failed, retrying if possible...

2025-08-22 08:12:44.657295+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

2025-08-22 08:12:45.658407+00:00 : (Connection) Attempt no.8 failed, retrying if possible...

2025-08-22 08:12:45.659402+00:00 : (Connection) Error : [Errno 111] Connect call failed ('127.0.0.1', 5432)

Traceback (most recent call last):
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 97, in connection_handler
    conn = await asyncpg.connect(CONNECTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/usr/lib/python3/dist-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5432)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 16, in main
    conn = await connection_handler()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 102, in connection_handler
    await asyncio.sleep(retry_delay)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 95, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt





2025-08-22 08:22:26.891662+00:00 : upload_to_database_historical.py has been initiated.

2025-08-22 08:22:26.895975+00:00 : (Connection) Error : [Errno 104] Connection reset by peer

2025-08-22 08:22:27.896167+00:00 : (Connection) Attempt no.1 failed, retrying if possible...

2025-08-22 08:22:27.898011+00:00 : (Connection) Error : [Errno 104] Connection reset by peer

2025-08-22 08:22:28.898434+00:00 : (Connection) Attempt no.2 failed, retrying if possible...

2025-08-22 08:22:31.056929+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:32.058056+00:00 : (Insertion) Attempt no.1 failed, retrying if possible...

2025-08-22 08:22:32.059245+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:33.060547+00:00 : (Insertion) Attempt no.2 failed, retrying if possible...

2025-08-22 08:22:33.061717+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:34.063103+00:00 : (Insertion) Attempt no.3 failed, retrying if possible...

2025-08-22 08:22:34.064450+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:35.064778+00:00 : (Insertion) Attempt no.4 failed, retrying if possible...

2025-08-22 08:22:35.066188+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:36.067526+00:00 : (Insertion) Attempt no.5 failed, retrying if possible...

2025-08-22 08:22:36.069534+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:37.071289+00:00 : (Insertion) Attempt no.6 failed, retrying if possible...

2025-08-22 08:22:37.072858+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:38.075119+00:00 : (Insertion) Attempt no.7 failed, retrying if possible...

2025-08-22 08:22:38.076537+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:39.079240+00:00 : (Insertion) Attempt no.8 failed, retrying if possible...

2025-08-22 08:22:39.080272+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:40.083317+00:00 : (Insertion) Attempt no.9 failed, retrying if possible...

2025-08-22 08:22:40.084344+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:22:41.087747+00:00 : (Insertion) Error unresolved - exiting program





/home/elnor/vivacity/upload_to_database_historical.py:18: RuntimeWarning: coroutine 'create_database_if_missing' was never awaited
  create_database_if_missing()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback





2025-08-22 08:50:39.344341+00:00 : upload_to_database_historical.py has been initiated.

2025-08-22 08:50:41.294968+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:42.296564+00:00 : (Insertion) Attempt no.1 failed, retrying if possible...

2025-08-22 08:50:42.298431+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:43.299691+00:00 : (Insertion) Attempt no.2 failed, retrying if possible...

2025-08-22 08:50:43.301232+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:44.302741+00:00 : (Insertion) Attempt no.3 failed, retrying if possible...

2025-08-22 08:50:44.304423+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:45.305848+00:00 : (Insertion) Attempt no.4 failed, retrying if possible...

2025-08-22 08:50:45.306880+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:46.308399+00:00 : (Insertion) Attempt no.5 failed, retrying if possible...

2025-08-22 08:50:46.309467+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:47.310634+00:00 : (Insertion) Attempt no.6 failed, retrying if possible...

2025-08-22 08:50:47.311601+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:48.312984+00:00 : (Insertion) Attempt no.7 failed, retrying if possible...

2025-08-22 08:50:48.314405+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:49.315663+00:00 : (Insertion) Attempt no.8 failed, retrying if possible...

2025-08-22 08:50:49.316687+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:50.318256+00:00 : (Insertion) Attempt no.9 failed, retrying if possible...

2025-08-22 08:50:50.319357+00:00 : (Insertion) Error : relation "vivacity_traffic" does not exist

2025-08-22 08:50:51.320851+00:00 : (Insertion) Error unresolved - exiting program










2025-08-22 09:16:21.619110+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:16:22.262324+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:16:23.216931+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:16:23.952797+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:16:24.660021+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:16:25.438694+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:16:26.264073+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:16:27.119633+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:16:27.914114+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:16:27.914147+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:25:56.411857+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:25:59.619525+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:26:00.999700+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:26:03.330884+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:26:04.438943+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:26:05.629926+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:26:06.411310+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:26:07.500426+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:26:08.409169+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:26:08.409192+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:44:15.853431+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:44:18.069700+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:44:18.981616+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:44:19.911824+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:44:20.945281+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:44:21.925809+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:44:23.022987+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:44:23.915499+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:44:26.556692+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:44:26.556720+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:44:56.844965+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:44:57.695795+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:44:58.526668+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:44:59.342722+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:45:00.563743+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:45:01.254877+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:45:01.783499+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:45:02.490349+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:45:03.102280+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:45:03.102295+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:47:28.572320+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:47:29.153329+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:47:30.085486+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:47:30.539784+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:47:31.302364+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:47:31.979905+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:47:33.135832+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:47:33.630692+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:47:34.089331+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:47:34.089346+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:48:54.573912+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:48:55.128985+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:48:55.950151+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:48:56.569475+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:48:57.423611+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:48:58.180698+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:48:58.802785+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:48:59.208756+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:48:59.826139+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:48:59.826154+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 09:50:04.514864+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 09:50:05.510969+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 09:50:06.021156+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 09:50:06.635741+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 09:50:07.452520+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 09:50:07.828111+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 09:50:08.240586+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 09:50:08.647669+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 09:50:09.072726+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 09:50:09.072750+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 10:20:02.608986+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 10:20:05.155650+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 10:20:06.560632+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 10:20:08.084267+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 10:20:08.895563+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 10:20:09.571786+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 10:20:10.181187+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 10:20:10.593228+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 10:20:11.099077+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 10:20:11.099100+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 10:21:49.469342+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 10:21:49.920528+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 10:21:50.470370+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 10:21:51.418778+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 10:21:51.994635+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 10:21:52.582357+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 10:21:53.093648+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 10:21:53.500636+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 10:21:54.215681+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 10:21:54.215693+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 10:37:54.548870+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 10:37:58.042245+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 10:37:58.718545+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 10:37:59.470282+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 10:38:00.391758+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 10:38:00.976636+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 10:38:01.615765+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 10:38:02.100616+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 10:38:02.715662+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 10:38:02.715684+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 10:40:37.458934+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 10:40:38.002807+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 10:40:38.613259+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 10:40:39.240409+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 10:40:39.946533+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 10:40:40.849031+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 10:40:41.654893+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 10:40:42.389213+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 10:40:42.806280+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 10:40:42.806319+00:00 : Exiting upload_to_database_historical.py...










2025-08-22 12:45:50.403811+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-22 12:45:53.060577+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-22 12:45:54.070887+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-22 12:45:56.994881+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-22 12:45:57.511782+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-22 12:45:58.410941+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-22 12:45:59.870887+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-22 12:46:00.602321+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-22 12:46:01.651521+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-22 12:46:01.651536+00:00 : Exiting upload_to_database_historical.py...





Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'
Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 1, in <module>
    from imports.upload_to_database_historical_helper import *
  File "/home/elnor/vivacity/imports/upload_to_database_historical_helper.py", line 4, in <module>
    import asyncpg
ModuleNotFoundError: No module named 'asyncpg'





2025-08-25 09:12:57.032098+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 09:12:57.985142+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 09:12:59.741696+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 09:13:00.853117+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 09:13:01.907651+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 09:13:02.797687+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 09:13:04.033531+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 09:13:04.957072+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 09:13:06.496542+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 09:13:06.496561+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 09:21:59.785812+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 09:22:00.469276+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 09:22:01.447864+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 09:22:04.907555+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 09:22:05.838835+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 09:22:07.673942+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 09:22:08.189524+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 09:22:08.709256+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 09:22:09.429106+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 09:22:09.429123+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 10:03:47.369609+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 10:03:49.839215+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 10:03:51.786173+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 10:03:52.436946+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 10:03:54.024972+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 10:03:54.627667+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 10:03:55.677237+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 10:03:56.434653+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 10:03:56.883502+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 10:03:56.883528+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 10:05:27.326596+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 10:05:28.050453+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 10:05:28.567025+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 10:05:29.174315+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 10:05:30.402257+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 10:05:30.884302+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 10:05:31.816077+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 10:05:32.219928+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 10:05:32.735832+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 10:05:32.735853+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 10:07:14.935925+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 10:07:16.427129+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 10:07:17.503695+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 10:07:18.826296+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 10:07:19.743654+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 10:07:20.284568+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 10:07:21.367020+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 10:07:21.850745+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 10:07:22.464288+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 10:07:22.464310+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 10:39:40.909863+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 10:39:42.700470+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 10:39:43.959344+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 10:39:44.615111+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 10:39:45.452294+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 10:39:45.905252+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 10:39:46.519561+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 10:39:47.331352+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 10:39:47.875687+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 10:39:47.875702+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 10:50:01.086900+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 10:50:04.415871+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 10:50:04.924918+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 10:50:05.531577+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 10:50:06.162175+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 10:50:06.620566+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 10:50:07.023702+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 10:50:07.430725+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 10:50:07.837731+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 10:50:07.837751+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 11:01:01.837878+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 11:01:02.381471+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 11:01:02.926237+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 11:01:03.483043+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 11:01:04.041291+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 11:01:04.521328+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 11:01:05.368280+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 11:01:06.037176+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 11:01:07.061273+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 11:01:07.061297+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 11:03:37.552885+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 11:03:38.383154+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 11:03:38.892568+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 11:03:39.367987+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 11:03:39.881870+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 11:03:40.257128+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 11:03:40.761906+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 11:03:41.171973+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 11:03:41.578528+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 11:03:41.578543+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 11:05:53.969724+00:00 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 11:05:57.157568+00:00 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 11:05:57.667024+00:00 : Successful insertion of bucket size = 60m at cycle = 2

2025-08-25 11:05:58.183893+00:00 : Successful insertion of bucket size = 60m at cycle = 3

2025-08-25 11:05:58.681429+00:00 : Successful insertion of bucket size = 60m at cycle = 4

2025-08-25 11:05:59.282539+00:00 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 11:05:59.693927+00:00 : Successful insertion of bucket size = 1440m at cycle = 2

2025-08-25 11:06:00.102741+00:00 : Successful insertion of bucket size = 1440m at cycle = 3

2025-08-25 11:06:00.615659+00:00 : Successful insertion of bucket size = 1440m at cycle = 4

2025-08-25 11:06:00.615677+00:00 : Exiting upload_to_database_historical.py...










2025-08-25 13:26:09.734772 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 13:26:12.605098 : (Response JSON) Error : Server returned an error:
failed To parse date range params with error: failed to parse date range params with error: failed to parse parameter 'from' with error: the time format '2025-08-18T13:00:00' is not supported, try '2006-01-02T15:04:05Z'

Traceback (most recent call last):
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 96, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/elnor/vivacity/upload_to_database_historical.py", line 56, in main
    for countline_id, entries in data.items():
                                 ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value





2025-08-25 13:55:06.771955 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 13:55:07.357235 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 13:55:07.826847 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 13:55:07.826865 : Exiting upload_to_database_historical.py...










2025-08-25 14:13:48.467821 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 14:13:50.247539 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 14:13:51.248541 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 14:13:51.248554 : Exiting upload_to_database_historical.py...










2025-08-25 14:19:14.211171 : upload_to_database_historical.py has been initiated.

About to start creating database
Creation attempt no. 0
Table created
2025-08-25 14:19:15.073079 : Successful insertion of bucket size = 60m at cycle = 1

2025-08-25 14:19:15.734814 : Successful insertion of bucket size = 1440m at cycle = 1

2025-08-25 14:19:15.734833 : Exiting upload_to_database_historical.py...





